<option value="school_items">school items</option>
<option value="class_projects">class projects</option>
<option value="clothing_handmade">clothing/handmade</option>
<option value="desserts">desserts</option>
<option value="entertainment">entertainment</option>
<option value="food">food</option>
<option value="health_beauty">health/beauty</option>
<option value="home_garden">home and garden</option>
<option value="jewelry">jewelry</option>
<option value="lessons">lessons and classes</option>
<option value="miscellaneous">miscellaneous</option>
<option value="pets">pets</option>
<option value="services">services</option>
<option value="recreation">sports and recreation</option>
<option value="technology">technology</option>
<option value="toys">toys</option>
<option value="tools">tools</option>
<option value="travel">travel</option>
